### ISSUE TITLE
Update for 0.16

### ISSUE THREAD

**Issue by alexdriedger** [manny405/sapai#32]
https://store.steampowered.com/news/app/1714040/view/4488403147907143669

- [x] Update pet values #36 
- [x] Update dragon, t-rex, and snail to not affect themselves #38 
- [ ] Honey badgers tie #37 
- [x] New peacock ability
- [ ] Rat summons dirty rat up front #57

**Comment by alexdriedger** [comment]
Created #38 and #37 for those specific updates

**Comment by alexdriedger** [comment]
Created issues for the remaining updates
