### ISSUE TITLE
v0.2.0 Checklist

### ISSUE THREAD

**Issue by manny405** [manny405/sapai#83]
v0.2.0 will include the following:

- [ ] More consistent implementation for effect looping for knockouts, hurt, and faint

- [ ] Extensive testing suite, verifying that all behaviors in battle of the standard pack have been implemented correctly

Subversion after will include implementations and extensive testing suite for the following:

- [ ] All behaviors of player and shop for standard pack have been implemented correctly
- [ ] All behaviors in battle of the expansion pack 1 have been implemented correctly
- [ ]  All behaviors of player and shop for expansion pack 1 have been implemented correctly

Proposing that v0.3.0 has the following

- [ ] Expansion pack 3
- [ ] Trained ML model based on millions of battles from v0.2.0 and full-game self-training
