### ISSUE TITLE
v1.0.0 Checklist

### ISSUE THREAD

**Issue by manny405** [manny405/sapai#84]
Proposing that v1.0.0 has the following

- [ ] Implementation for all pets, including expansion pack 3
- [ ] Full testing in battle and in shop
- [ ] Fully tested battle modes
- [ ] Trained ML model based on millions of battles and full-game self-training
